packages:
  - "packages/*"
  - "apps/*"
allowBuilds:
  "@google/genai": true
  "@mongodb-js/zstd": true
  esbuild: true
  node-liblzma: true
  protobufjs: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@^0.1.20
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
